### ISSUE TITLE
PortfolioSlider - problems with applying styles

### ISSUE THREAD

**Issue by fromITzerotoIThero** [fromITzerotoIThero/personal-website#1]
Hey W.!

Thought I'd try out this Issues features to ask you some of the questions that arise :)
At first I started working on different branches and thought I'd keep creating PRs, but since I don't need the answers ASAP, this seemed to be an option to go for :)

So I created the first version of a PortfolioSlider component - it's not perfect, but kinda does the job. 
I have issues with styling though:

1. I can't find a way to target the navigation bullets and the arrows. 
- I've managed to reference the bullets in he "inactive' state, but by no means the 'active' one (.container_internal li.slick-active button::before didn't work)
- there seems to be some way of going about it with the use of "settings" objects, where I pass configuration options for the carousel, but it seems a bit convoluted (and I guess I'd simply like to know how to target different elements that come from a library)

I'd very much appreciate your comments, but no need to rush! :)

**Comment by piotrwicijowski** [comment]
Use `:global()` in css module to style if you want to target styles that you do not control
