### ISSUE TITLE
Commit mess - accidentally made one huge commit and pushed it on master

### ISSUE THREAD

**Issue by fromITzerotoIThero** [fromITzerotoIThero/personal-website#2]
W., 
By mistake I staged, commited and pushed many many changes on master instead of making one tiny commit. I thought I might revert it somehow, but my gut instinct tells me not to do it, that it may cause more problems than it will solve. Am I right?

**Comment by piotrwicijowski** [comment]
Depending on what was your intention - if the changes that you made were actually really temporary and exploratory, and that they would break the webpage, then yes, I suggest reverting. But If all of those changes are valid, then you need to ask yourself a question - "what is my goal right now?" Do you want to learn about git, best practices, and workflow, or do you want to push your webpage forward as fast as possible?

**Comment by fromITzerotoIThero** [comment]
Oh W., you're such a good mentor! 🚀 👏 
That was just the advice I needed! Thx!
