### ISSUE TITLE
Switching to NavLinks - navigation doesn't work

### ISSUE THREAD

**Issue by fromITzerotoIThero** [fromITzerotoIThero/personal-website#4]
W., 

Another issue - I've switched from classical `a` elements to `NavLinks`, but for some reason it broke the navigation.
- `a` elements worked fine, navigating to proper sections based on their ids
- clicking on NavLinks does change the URL properly. yet it doesn't cause any navigation
- my troubleshooting with React Router docs and Chat GPT didn't help

I'd very much appreciate your advice - can be general, for the direction to go.

**Comment by piotrwicijowski** [comment]
Hmm it seems that my assumptions that "using #id would just work" was false. There has been an old ongoing issue with react router, and it seems they don't support it. So you have two options:
1. Get back to using `<a>`
2. Use another npm package https://github.com/rafgraph/react-router-hash-link that has this feature implemented

**Comment by fromITzerotoIThero** [comment]
Oh thank you, I'll check out this hash-link library and decide on one of these :)
